language: ruby
rvm:
- 2.3.3
dist: precise
addons:
  apt:
    packages:
    - python3
    - python3-yaml
before_install:
- openssl aes-256-cbc -K $encrypted_22f1d25dd78b_key -iv $encrypted_22f1d25dd78b_iv
  -in deploy_key.enc -out deploy_key -d
before_script:
- chmod +x ./scripts/build/csvcheck.rb
- chmod +x ./scripts/build/cibuild
script:
- ruby ./scripts/build/csvcheck.rb
- python3 ./scripts/build/metadatacheck.py
- "./scripts/build/cibuild"
after_success:
- chmod +x ./scripts/deploy.sh
- scripts/deploy.sh
branches:
  only:
  - gh-pages
  - "/pages-(.*)/"
  - deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
