language: ruby
rvm:
- 2.4.0
dist: trusty
addons:
  apt:
    packages:
    - python3
    - python3-yaml
    - python3-setuptools
    - python3-pandas
before_script:
- chmod +x ./scripts/build/csvcheck.py
- chmod +x ./scripts/build/cibuild.sh
script:
- python3 ./scripts/build/csvcheck.py
- python3 ./scripts/build/metadatacheck.py
- scripts/build/cibuild.sh
after_success:
- chmod +x ./scripts/deploy/deploy.sh
- scripts/deploy/deploy.sh
branches:
  only:
  - gh-pages
  - "/pages-(.*)/"
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
