# Welcome to Jekyll!
#
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
environment: production
remotedatabaseurl: "https://sdg.mango-solutions.com/data/8-6-1-catch-all"
# permalink: /news/:year/:month/:day/:title.html

jekyll_get_json:
  - data: meta
    json: "https://sdg.mango-solutions.com/data/8-6-1-catch-all/meta/all.json"
    # cache: true
    # directory: 'remotedata'
  - data: headlines
    json: 'https://sdg.mango-solutions.com/data/8-6-1-catch-all/headline/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: schema
    json: 'https://sdg.mango-solutions.com/data/8-6-1-catch-all/meta/schema.json'
  - data: translations
    # Pin to version of the translation repository.
    json: 'https://open-sdg.github.io/sdg-translations/translations-0.4.0.json'

analytics:
  ga_prod: 'UA-108503280-1'
