# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: U.K. Indicators For The Sustainable Development Goals
description: Data Platform Prototype
url: ""
data_dir: data

#Github Repo
repo_name: sdg-indicators
branch: gh-pages
org_name: datasciencecampus

# Build settings
markdown: kramdown

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  indicators:
    output: true
  goals:
    output: true

# Prose configuration
prose:
  ignore: ['/assets', '/_includes', '/_layouts', '/scripts', '/sass' ]
  metadata:
    _indicators:
      - name: "indicator_name"
        field: 
            element: text
            label: "SDG Indicator Name"
            scope: global
      - name: "target"
        field: 
            element: text
            label: "SDG Target Addressed"
            scope: global
      - name: "indicator_definition"
        field: 
            element: textarea
            label: "Definition of SDG Indicator"
            scope: global
      - name: "method_of_computation"
        field: 
            element: textarea
            label: "Method of computation for global SDG indicator"
            scope: global
      - name: "un_designated_tier"
        field: 
            element: text
            label: "UN Designated Tier"
            scope: global
      - name: "un_custodial_agency"
        field: 
            element: text
            label: "UN Custodial Agency"
            scope: global
      - name: "graph_title"
        field: 
            element: text
            label: "Graph Title"  
      - name: "actual_indicator_available"
        field:
            element: text
            label: "Actual indicator available"
      - name: "actual_indicator_available_description"
        field: 
            element: textarea
            label: "Description of actual indicator available"  
        field:
            element: text
            label: "Description of actual indicator available"
      - name: "us_method_of_computation"
        field:
            element: textarea
            label: "Method of computation"
      - name: "comments_and_limitations"
        field: 
            element: textarea
            label: "Comments and limitations"  
      - name: "periodicity"
        field:
            element: text
            label: "Periodicity"
      - name: "time_period"
        field:
            element: text
            label: "Time Period"
      - name: "unit_of_measure"
        field:
            element: text
            label: "Unit of measure"
      - name: "disaggregation_categories"
        field:
            element: text
            label: "Disaggregation #1 (Industry or social categories)"
      - name: "disaggregation_geography"
        field:
            element: text
            label: "Disaggregation #2 (Geographical coverage)"
      - name: "date_of_national_source_publication"
        field:
            element: text
            label: "Date of public data release from National source"
            placeholder: "MONTH YEAR"
      - name: "date_metadata_updated"
        field:
            element: text
            label: "Date of last Update of This Page"
            placeholder: "MONTH YEAR"
      - name: "scheduled_update_by_national_source"
        field:
            element: text
            label: "Scheduled Update by National source"
            placeholder: "MONTH/YEAR (Next Agency Release)"
      - name: "scheduled_update_by_SDG_team"
        field:
            element: text
            label: "Scheduled Update by SDG Team"
            placeholder: "MONTH/YEAR (NRP Database)"
      - name: "source_agency_staff_name"
        field:
            element: text
            label: "Data Source1 (Agency STAFF NAME)"
      - name: "source_agency_staff_email"
        field:
            element: text
            label: "Data Source2 (Staff E-MAIL)"
      - name: "source_agency_survey_dataset"
        field:
            element: text
            label: "Data Source3 (Agency/Survey/Dataset name)"
      - name: "source_url"
        field:
            element: text
            label: "Indicator web address (closest to data provided)"   
      - name: "international_and_national_references"
        field:
            element: text
            label: "International and National References"
