# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: U.K. Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
data_dir: data
environment: production
# permalink: /news/:year/:month/:day/:title.html

analytics:
  ga_prod: 'UA-108503280-1'

###################################################################################################
email_contacts:
  questions: email@email.com
  suggestions: email@email.com
  functional: email@email.com
###################################################################################################

#Github Repo
repo_name: sdg-indicators
branch: develop
org_name: datasciencecampus

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: UK
  adjective: UK

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Prose configuration
prose:
  ignore: ['/assets', '/_includes', '/_layouts', '/scripts', '/sass' ]
  metadata:
    _indicators:
    ############ Page Data ############
      - name: "title"
        field:
            element: text
            label: "Page Title"
            scope: page
      - name: "sdg_goal"
        field:
            element: hidden
            label: "SDG Goal"
            scope: page
      - name: "permalink"
        field:
            element: hidden
            label: "Permalink"
            scope: page
      - name: "layout"
        field:
            element: hidden
            label: "Layout"
            scope: page
    ######### Global Metadata #########
      - name: "indicator_name"
        field:
            element: text
            label: "Indicator name"
            scope: global
      - name: "indicator"
        field:
            element: hidden
            label: "Indicator number"
            scope: global
      - name: "target"
        field:
            element: text
            label: "Target name"
            scope: global
      - name: "target_id"
        field:
            element: text
            label: "Target number"
            scope: global
      - name: "indicator_definition"
        field:
            element: textarea
            label: "Global indicator description"
            scope: global
      - name: "un_designated_tier"
        field: 
            element: text
            label: "UN designated tier"
            scope: global
      - name: "un_custodian_agency"
        field: 
            element: text
            label: "UN custodian agency"
            scope: global
      - name: "goal_meta_link"
        field:
            element: text
            label: "Link to UN metadata"
            scope: global
      - name: "goal_meta_link_text"
        field:
            element: text
            label: "Link to UN metadata text"
            value: "UN metadata"
            scope: global
      ######### National Metadata #########
      - name: "national_indicator_available"
        field:
            element: text
            label: "Indicator available"
            scope: national
      - name: "national_indicator_description"
        field:
            element: text
            label: "Indicator description"
            scope: national
      - name: "national_geographical_coverage"
        field:
            element: text
            label: "Geographical coverage"
            scope: national
      - name: "computation_units"
        field:
            element: text
            label: "Unit of measurement"
            scope: national
      - name: "computation_definitions"
        field:
            element: textarea
            label: "Definitions"
            scope: national
      - name: "computation_calculations"
        field:
            element: text
            label: "Calculations"
            scope: national
      - name: "comments_limitations"
        field:
            element: text
            label: "Other information"
            scope: national
      - name: "admin_release_date"
        field:
            element: text
            label: "Last updated"
            help: "A date in YYYY-MM-DD format"
            placeholder: "YYYY-MM-DD"
            scope: national
      ######### National Sources #########
      ## Source 1
      - name: source_active_1
        field:
            element: checkbox
            label: Source 1 active
            help: Whether or not to display this source
            value: true
      - name: source_organisation_1
        field:
            element: text
            label: "Organisation"
            scope: source_1
      - name: "source_periodicity_1"
        field:
            element: text
            label: "Periodicity"
            scope: source_1
      - name: "source_earliest_available_1"
        field:
            element: text
            label: "Earliest available data"
            scope: source_1
      - name: "source_geographical_coverage_1"
        field:
            element: text
            label: "Geographical coverage"
            scope: source_1
      - name: "source_url_1"
        field:
            element: text
            label: "Link to data source"
            scope: source_1
      - name: "source_url_text_1"
        field:
            element: text
            label: "Link to data source text"
            value: "Link to source"
            scope: source_1
      - name: "source_release_date_1"
        field:
            element: text
            label: "Release date"
            help: "A date in YYYY-MM-DD format"
            placeholder: "YYYY-MM-DD"
            scope: source_1
      - name: "source_next_release_1"
        field:
            element: text
            label: "Next release"
            help: "A date in YYYY-MM-DD format"
            placeholder: "YYYY-MM-DD"
            scope: source_1
      - name: "source_statistical_classification_1"
        field:
            element: text
            label: "Statistical classification"
            scope: source_1
      - name: "source_contact_1"
        field:
            element: text
            label: "Contact details"
            scope: source_1
      - name: "source_other_info_1"
        field:
            element: textarea
            label: "Other information"
            scope: source_1
      ## Source 2
      - name: source_active_2
        field:
            element: checkbox
            label: Source 2 active
            help: Whether or not to display this source
            value: false
      - name: source_organisation_2
        field:
            element: text
            label: "Organisation"
            scope: source_2
      - name: "source_periodicity_2"
        field:
            element: text
            label: "Periodicity"
            scope: source_2
      - name: "source_earliest_available_2"
        field:
            element: text
            label: "Earliest available data"
            scope: source_2
      - name: "source_geographical_coverage_2"
        field:
            element: text
            label: "Geographical coverage"
            scope: source_2
      - name: "source_url_2"
        field:
            element: text
            label: "Link to data source"
            scope: source_2
      - name: "source_url_text_2"
        field:
            element: text
            label: "Link to data source text"
            value: "Link to Source"
            scope: source_2
      - name: "source_release_date_2"
        field:
            element: text
            label: "Release date"
            help: "A date in YYYY-MM-DD format"
            placeholder: "YYYY-MM-DD"
            scope: source_2
      - name: "source_next_release_2"
        field:
            element: text
            label: "Next release"
            help: "A date in YYYY-MM-DD format"
            placeholder: "YYYY-MM-DD"
            scope: source_2
      - name: "source_statistical_classification_2"
        field:
            element: text
            label: "Statistical classification"
            scope: source_2
      - name: "source_contact_2"
        field:
            element: text
            label: "Contact details"
            scope: source_2
      - name: "source_other_info_2"
        field:
            element: textarea
            label: "Other information"
            scope: source_2
      ## Source 3
      - name: source_active_3
        field:
            element: checkbox
            label: Source 3 active
            help: Whether or not to display this source
            value: false
      - name: source_organisation_3
        field:
            element: text
            label: "Organisation"
            scope: source_3
      - name: "source_periodicity_3"
        field:
            element: text
            label: "Periodicity"
            scope: source_3
      - name: "source_earliest_available_3"
        field:
            element: text
            label: "Earliest available data"
            scope: source_3
      - name: "source_geographical_coverage_3"
        field:
            element: text
            label: "Geographical coverage"
            scope: source_3
      - name: "source_url_3"
        field:
            element: text
            label: "Link to data source"
            value: "Link to source"
            scope: source_3
      - name: "source_url_text_3"
        field:
            element: text
            label: "Link to data source text"
            scope: source_3
      - name: "source_release_date_3"
        field:
            element: text
            label: "Release date"
            help: "A date in YYYY-MM-DD format"
            placeholder: "YYYY-MM-DD"
            scope: source_3
      - name: "source_next_release_3"
        field:
            element: text
            label: "Next release"
            help: "A date in YYYY-MM-DD format"
            placeholder: "YYYY-MM-DD"
            scope: source_3
      - name: "source_statistical_classification_3"
        field:
            element: text
            label: "Statistical classification"
            scope: source_3
      - name: "source_contact_3"
        field:
            element: text
            label: "Contact details"
            scope: source_3
      - name: "source_other_info_3"
        field:
            element: textarea
            label: "Other information"
            scope: source_3
      ######### Data Info #########
      - name: "data_edge_list"
        field: 
            element: text
            label: "Data hierachy edge list"
      - name: "reporting_status"
        field: 
            element: select 
            label: "Reporting status"
            options:
              - name: 'notstarted'
                value: 'notstarted'
              - name: 'inprogress'
                value: 'inprogress'
              - name: 'complete'
                value: 'complete'
      - name: data_non_statistical
        field:
            element: checkbox
            label: Non-statistical indicator
            help: Check this box if this indicator does not have numeric data associated with it
            value: false
      - name: data_footnote
        field:
            element: text
            label: Footnote
            help: Footnotes appear under the chart and by data tables
      ######### Chart Info #########
      - name: "graph_type"
        field: 
            element: select 
            label: "Graph type"
            options:
              - name: 'line'
                value: 'line'
              - name: 'bar'
                value: 'bar'
      - name: "graph_title"
        field: 
            element: text
            label: "Graph Title"
    
