# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
environment: production
remote_data_prefix: "https://sdgdata.gov.uk/sdg-data"

reporting_status:
    description: |

      Reporting status provides an overview of how much Sustainable Development Goal (SDG) data the UK reports. For more information, see [What does the reporting status mean?](https://sdgdata.gov.uk/faq/#what-does-the-reporting-status-mean)

      Disaggregation status provides an overview of how many of the SDG indicators are disaggregated. For more information, see [What does the disaggregation status mean?](https://sdgdata.gov.uk/faq/#what-does-the-disaggregation-status-mean)

      For details about all available disaggregations and how each indicator is disaggregated, see the [UK disaggregation report](https://sdgdata.gov.uk/sdg-data/disaggregations.html).

      Note: These percentages have been rounded. As a result, adding them together may not equal exactly 100%.

analytics:
  ua: UA-108503280-1
  gtag: G-JP2PR9QKW9

hotjar: true
