analytics:
  ua: ''
  gtag: ''
  gtm: ''
breadcrumbs:
  goal: []
  indicator: []
  post: []
cookie_consent_form:
  enabled: true
country:
  name: UK
  adjective: UK
create_goals:
  previous_next_links: false
  goals:
    - goal: 1
      content: >-
        
        Goal 1 calls for the eradication of poverty in all its forms. It envisions:
        
        -	shared prosperity
        
        -	a basic standard of living
        
        -	social protection benefits for people everywhere - including the poorest and most vulnerable
        
        It also seeks to ensure equal rights and access to economic and natural resources.
    - goal: 2
      content: >-
        
        Goal 2 seeks to:
        
        -	end hunger and malnutrition
        
        -	ensure access to safe, nutritious, and sufficient food
        
        
        Achieving this goal will largely depend on:
        
        -	promoting sustainable production systems
        
        -	increasing investment in rural infrastructure and agricultural research and development
    - goal: 3
      content: >-
        
        Goal 3 aims to ensure the health and promote the well-being of everyone (of all ages) by:
        
        -	improving reproductive, maternal and child health
        
        -	ending epidemics of major contagious diseases
        
        -	reducing non-contagious diseases
        
        -	promoting mental health and well-being
        
        -	reducing behavioural and environmental health-risk factors
    - goal: 4
      content: >-
        
        Goal 4 seeks to:
        
        -	ensure access to fair, impartial and quality education through all stages of life
        
        -	increase the number of young people and adults who have the relevant skills for employment, decent jobs, and entrepreneurship
        
        -	eliminate gender and income disparities in access to education
    - goal: 5
      content: >-
        
        Goal 5 aims to achieve gender equality by:
        
        -	ending all forms of discrimination, violence and harmful practices against women and girls
        
        -	ensuring the full participation of women and equal opportunities for leadership at all levels of political and economic decision making
    - goal: 6
      content: >-
      
        Goal 6 calls for ensuring universal access to:
        
        -	safe and affordable drinking water 
        
        -	sanitation and hygiene
        
        It also aims to:
        
        -	end defecation in the open
        
        -	improve water quality and water use efficiency 
        
        -	encourage sustainable abstractions and supply of freshwater
    - goal: 7
      content: >-
      
        Goal 7 calls for:
        
        -	ensuring universal access to modern energy services
        
        -	improving energy efficiency
       
        -	increasing the share of renewable energy
        
        
        To accelerate the transition to an affordable, reliable and sustainable energy system that fulfils these demands countries need to:
        
        -	 facilitate access to clean energy research and technology 
        
        -	 promote investment in resource and energy-efficient solutions and related infrastructure
    - goal: 8
      content: >-
      
        Goal 8 recognises the importance of sustained economic growth and high levels of economic productivity for:
        
        -	the creation of well-paid quality jobs 
        
        -	progressive improvement of resource efficiency in consumption and production
        
        
        It calls for: 
        
        -	opportunities for full employment and decent work for all 
        
        -	the eradication of forced labour, human trafficking and child labour
        
        -	the promotion of labour rights and safe and secure working environments
    - goal: 9
      content: >-
      
        Goal 9 calls for building resilient and sustainable infrastructure and promotes inclusive and sustainable industrialisation.
        It also recognises the importance of research and innovation for finding lasting solutions to social, economic, and environmental challenges.  
    - goal: 10
      content: >-
      
        Goal 10 addresses inequalities within countries, including:
        
        -	income 
        
        -	age
        
        -	sex
        
        -	disability
        
        -	race
        
        -	ethnicity
        
        -	origin
        
        -	religion
        
        -	economic 
        
        -	any other status 
        
        
        It also addresses inequalities among countries (including those related to representation) and calls for the orderly and safe migration 
        and mobility of people.
    - goal: 11
      content: >-
        
        Goal 11 aims to renew and plan cities and other human settlements in a way that offers opportunities for all, whilst reducing resource use 
        and environmental impact. It calls for access for all to:
        
        -	basic services
        
        -	energy 
        
        -	housing
        
        -	transportation
        
        -	green public spaces
    - goal: 12
      content: >-
        
        Goal 12 calls for a comprehensive set of actions from businesses, policy-makers, researchers, and consumers to adapt to sustainable practices. 
        It envisions sustainable production and consumption based on advanced technological capacity, resource efficiency and reduced global waste.
    - goal: 13
      content: >-
        
        Goal 13 seeks to implement the commitment of the United Nations Framework Convention on Climate Change to achieving a climate-neutral world. 
        
        
        With a particular focus on supporting the least developed countries, it also aims to strengthen countries’ resilience and adaptive capacity to climate-related natural hazards and the resulting disasters.
    - goal: 14
      content: >-
        
        Goal 14 aims to protect and ensure the sustainable use of oceans. This includes:
        
        -	the reduction of marine pollution
        
        -	the impacts of ocean acidification
        
        -	the ending of overfishing
        
        -	the conservation of marine and coastal areas and ecosystems
        
        
        Goal 14 has strong interdependencies with a broad range of other Sustainable Development Goals (SDGs), as oceans:
        
        -	sustain coastal economies and livelihoods
        
        -	contribute to food production
        
        -	remove carbon dioxide from the atmosphere
    - goal: 15
      content: >-
        
        Goal 15 seeks to protect, restore, and promote the conservation and sustainable use of terrestrial, inland-water and mountain ecosystems by:
        
        -	managing forests sustainably
        
        -	halting deforestation
        
        -	combating desertification
        
        -	restoring degraded land and soil
        
        -	halting biodiversity loss 
        
        -	protecting threatened species
    - goal: 16
      content: >-
        
        Goal 16 calls for peaceful and inclusive societies based on:
        
        -	respect for human rights
        
        -	the protection of the most vulnerable
        
        -	the rule of law and good governance at all levels
        
        
        It also envisions transparent, effective, and accountable institutions.
    - goal: 17
      content: >-
      
        Goal 17 calls for a global partnership for sustainable development. The goal highlights the importance of:
        
        -	global macroeconomic stability
        
        -	trade for developing countries 
        
        -	equitable rules for governing international trade 
        
        -	access to science, technology and innovation - particularly internet-based information and communications technology
        
        
        The goal also highlights the need to mobilise financial resources for developing countries from international sources (and through strengthened 
        domestic capacities) for revenue collection. 
layout: goal-by-target-vertical
create_indicators:
  previous_next_links: false
  layout: indicator
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: UK data for the Sustainable Development Goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: Reporting Status
  - filename: ''
    folder: /search
    layout: search
    title: Search results
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: ''
data_fields:
  units: ''
  series: ''
date_formats:
  - type: standard
    language: en
    format: '%d %B %Y'
disclaimer:
  phase: BETA
  message: >-
    This website is in development – your <a
    href="https://www.surveymonkey.co.uk/r/SDGfeedback">feedback</a> will help
    us to improve it
  hidden: false
email_contacts:
  questions: sustainabledevelopment@ons.gov.uk
  suggestions: sustainabledevelopment@ons.gov.uk
  functional: sustainabledevelopment@ons.gov.uk
environment: staging
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: 'https://twitter.com/ONS'
    translation_key: general.twitter
  - path: /cookies-no-javascript/
    translation_key: menu.cookies
  - path: /privacy-notice/
    translation_key: Privacy
  - path: /accessibility-statement/
    translation_key: Accessibility statement
frontpage_cards:
  - title: Download all data
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Publications
    content: >

      [SDGs in the UK: Progress on monitoring and reporting
      data](https://www.ons.gov.uk/economy/environmentalaccounts/articles/sustainabledevelopmentgoalstakingstockprogressandpossibilities/december2020)


      [UK SDG Voluntary National
      Review](https://www.gov.uk/government/publications/uks-voluntary-national-review-of-the-sustainable-development-goals)

      <br/><br/>

      <a href="./publications" aria-label="More publications">More
      publications...</a>
    include: ''
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Useful resources
    content: >

      [The Global Goals](https://www.globalgoals.org/)


      [Implementing the Sustainable Development
      Goals](https://www.gov.uk/government/publications/implementing-the-sustainable-development-goals/implementing-the-sustainable-development-goals--2)


      [UN Department of Economic and Social Affairs](https://sdgs.un.org/)
    include: ''
    button_label: ''
    button_link: ''
    rule_color: ''
frontpage_goals_grid:
  title: UK data for the Sustainable Development Goals
  description: >-
    Select each goal for indicator data.
frontpage_introduction_banner:
  title: 17 goals to transform our world
  description: >-
    Welcome to the home of UK data for <a href="https://sdgs.un.org/goals">the Sustainable Development Goals (SDGs)</a>
    – reported by <a href="https://www.ons.gov.uk/">the Office for National Statistics</a>, 
    the UK’s national statistics institute.
    
    
    The Sustainable Development Goals (SDGs) are a universal call to action
    to end poverty, protect the planet and improve the lives and prospects
    of everyone, everywhere. The 17 Goals
    were adopted by all UN Member States in 2015, as part of the <a
    href="https://sdgs.un.org/2030agenda">2030 Agenda for Sustainable
    Development</a>.
    
    
    UK data for the Sustainable Development Goals are collated and reported here.
goal_image_base: 'https://open-sdg.github.io/sdg-translations/assets/img/goals'
goal_image_extension: svg
goals_page:
  title: UK data for the Sustainable Development Goals
  description: >-
    Select each goal for indicator data.
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: true
header_language_toggle: none
hide_empty_metadata: false
hide_single_series: true
hide_single_unit: true
ignored_disaggregations:
  - Activity (default)
  - Age (default)
  - Urbanisation (default)
indicator_config_form:
  enabled: false
  dropdowns: []
  repository_link: ''
  translation_link: ''
indicator_data_form:
  enabled: false
  repository_link: ''
indicator_metadata_form:
  enabled: false
  dropdowns: []
  repository_link: ''
  translation_link: ''
  language: ''
  scopes: []
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - en
languages_public: []
logos: []
map_layers:
  - subfolder: country
    label: Country
    min_zoom: 4
    max_zoom: 6
    staticBorders: true
  - subfolder: regions
    label: Regions
    min_zoom: 6
    max_zoom: 8
    staticBorders: true
  - subfolder: local_authorities
    label: Local Authorities
    min_zoom: 9
    max_zoom: 12
    staticBorders: true
map_options:
  disaggregation_controls: false
  minZoom: 4
  maxZoom: 10
  tileURL: 'https://{s}.tile.jawg.io/{id}/{z}/{x}/{y}{r}.png?access-token={accessToken}'
  tileOptions:
    id: ed56748f-29f9-465e-9269-c715674ee5ff
    accessToken: yrcGMvxCkRD6zZBF4x3mnAT3OGQJstAj7JvG1iy1UjEdy6JFeDfnzKvXrTK07CxF
    attribution: >-
      <a href="http://jawg.io" title="Provider of map tiles"
      target="_blank">&copy; <b>Jawg</b>Maps</a> &copy; <a
      href="https://www.openstreetmap.org/copyright" title="Provider of map visual data copywrite information">OpenStreetMap</a>
      contributors | <a href="http://geoportal.statistics.gov.uk/" title="The Open Geography portal from the Office for National Statistics">ONS</a>
  colorRange: 
    -  '#c4e1c6'
    -  '#b0d1b3'
    -  '#9bc2a1'
    -  '#87b28f'
    -  '#74a37c'
    -  '#60946b'
    -  '#4d8559'
    -  '#3a7747'
    -  '#276836'
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status/
    translation_key: menu.reporting_status
    dropdown: []
  - path: /about/
    translation_key: menu.about
    dropdown: []
  - path: /publications/
    translation_key: menu.publications
    dropdown: []
  - path: /faq/
    translation_key: menu.faq
    dropdown: []
  - path: /updates/
    translation_key: menu.updates
    dropdown: []
metadata_edit_url: ''
metadata_tabs: []
news:
  category_links: false
progress_status:
  status_heading: ''
  status_types: []
remote_data_prefix: >-
  https://ONSdigital.github.io/sdg-data
reporting_status:
  title: Reporting status
  description: >

    Reporting status provides an overview of how much Sustainable Development
    Goal (SDG) data the UK reports. For more information, see [What does the
    reporting status
    mean?](https://onsdigital.github.io/sdg-indicators/faq/#what-does-the-reporting-status-mean)



    Disaggregation status provides an overview of how many of the SDG indicators
    are disaggregated. For more information, see [What does the disaggregation
    status
    mean?](https://onsdigital.github.io/sdg-indicators/faq/#what-does-the-disaggregation-status-mean)



    For details about all available disaggregations and how each indicator is
    disaggregated, see the [UK disaggregation
    report](https://onsdigital.github.io/sdg-data/disaggregations.html).



    Note: These percentages have been rounded. As a result, adding them together
    may not equal exactly 100%.
  disaggregation_tabs: true
  status_types:
    - value: complete
      label: status.reported
      hide_on_goal_pages: false
    - value: notstarted
      label: status.no_data_available
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/ONSdigital/sdg-data'
repository_url_site: 'https://github.com/ONSdigital/sdg-indicators'
search_index_boost: []
search_index_extra_fields:
  - indicator_available
  - graph_title
  - data_keywords
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: '/tree/develop/_data'
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''

