name: sdg
channels:
- defaults
dependencies:
- dateutil=2.4.1=py34_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- ncurses=6.0=ha932d30_1
- numpy=1.8.1=py34_0
- openssl=1.0.1k=1
- pandas=0.13.1=np18py34_0
- pip=9.0.1=py34_1
- python=3.4.0=0
- pytz=2017.2=py34_0
- pyyaml=3.10=py34_0
- readline=6.2=2
- scipy=0.14.0=np18py34_0
- setuptools=27.2.0=py34_0
- six=1.10.0=py34_0
- sqlite=3.20.1=h900c3b0_1
- tk=8.5.18=0
- wheel=0.29.0=py34_0
- yaml=0.1.4=1
- zlib=1.2.11=h60db283_1
- pip:
  - python-dateutil==2.4.1
prefix: /Users/douglas/anaconda3/envs/sdg

