name: Deploy feature branch to S3

on:
  push:
    branches:
      - 'feature-*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Update the baseurl
        uses: fjogeleit/yaml-update-action@master
        with:
          # Update this if your 'baseurl' setting is in a different file.
          valueFile: '_config.yml'
          propertyPath: 'baseurl'
          value: '/${{ env.GITHUB_REF_SLUG }}'
          commitChange: 'false'
          updateFile: 'true'
      - name: Update the remote_data_prefix
        uses: fjogeleit/yaml-update-action@master
        if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'feature-site-') == false
        with:
          # Update this if your 'remote_data_prefix' setting is in a different file.
          valueFile: '_config.yml'
          propertyPath: 'remote_data_prefix'
          # Update this according to the public URL of your S3 bucket.
          value: 'http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/${{ env.GITHUB_REF_SLUG }}-data'
          commitChange: 'false'
          updateFile: 'true'
      - name: Build the site
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
          bundle exec jekyll build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          # Update this according to the name of your S3 bucket.
          AWS_S3_BUCKET: uk-sdg-feature-branches
          # Don't forget to set AWS_ACCESS as a "repository secret".
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS }}
          # Don't forget to set AWS_SECRET as a "repository secret".
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          SOURCE_DIR: _site
          DEST_DIR: ${{ env.GITHUB_REF_SLUG }}
      - name: Send message to Slack channel
        uses: archive/github-actions-slack@v2.2.1
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: CP95DHDLY
          slack-text: Your feature branch is available at http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/${{ env.GITHUB_REF_SLUG }}
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
