name: Test Push or Pull Request

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: ruby/setup-ruby@v1
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Build the site
      run: |
        gem install bundler
        bundle config path vendor/bundle
        make install
        make build.staging
    - name: Test the HTML
      run: bash scripts/test/html_proofer_staging.sh
